baseURL = "https://nrsprs.github.io/"
languageCode = "en"
title = "Nick Spears - Robtics Software Developer"

[params]
    name = "Nick Spears"
    description = "Robotics Software Developer"
    email = "nicholas.sprs@gmail.com"
    address = "190 Lomb Memorial Drive, Rochester, NY"
    year = 2024
    avatar = "/images/green_wall_cropped_800x.png"
    avatarclass = "circle"
    background = ""
    banner = "/images/banner.jpg"
    favicon = "/images/joe-cool-snoopy.png"
    DateForm = "Aug 1, 2024"
    author = "Nick Spears"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = false
    showClients = false

    showFooterContact = false
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickspears"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/nrsprs"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"